#!/usr/bin/python -u
#
# CS3700, Spring 2015
# Project 2 Starter Code
#

import sys
import socket
import time
import datetime
import select
import json

def log(string):
    sys.stderr.write(datetime.datetime.now().strftime("%H:%M:%S.%f") + " " + string + "\n")

MSG_SIZE = 1500
MSS = 1500 - 2*sys.getsizeof(int()) - 3*sys.getsizeof(bool()) - 20   # MTU - header fields

TIMEOUT = 30
syn_num = 0
buffer = {}

# Bind to localhost and an ephemeral port
UDP_IP = "127.0.0.1"
UDP_PORT = 0

# Set up the socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind((UDP_IP, UDP_PORT))
sock.settimeout(TIMEOUT)

# Get port we bound to
UDP_PORT = sock.getsockname()[1]
log("[bound] " + str(UDP_PORT))

#Next expected sequence number
expected_sequence = 0

def print_buffered_packets(seq):
    global expected_sequence
    next_data = buffer.get(seq, None)
    if next_data:
        sys.stdout.write(next_data)
        log("[unbuffered] " + str(seq))
        del buffer[seq]
        print_buffered_packets(seq + len(next_data))
    else: # if there's no buffered data left to be printed, expected_sequence should now be at seq
        expected_sequence = seq


# Now listen for packets
while True:
    result = sock.recvfrom(MSG_SIZE)

    # If nothing is ready, we hit the timeout
    if result:
        (data, addr) = result

        try:
            decoded = json.loads(data)

            # If the FIN flag is set, exit
            if (decoded['fin'] and decoded['seq_num'] == expected_sequence):
                log("[completed] " + str(decoded))
                log("[fin buffer] " + str(buffer))
                msg = json.dumps({"fin": True, "ack": expected_sequence + 1})
                sock.sendto(msg, addr)
                sys.exit(0)

            if (decoded['syn']):
                # log("Starting connection...")
                syn_num = decoded['seq_num'] + 1
                expected_sequence = decoded['seq_num'] + 1
                msg = json.dumps({"syn": True, "ack": decoded['seq_num']+1, "fin": False})
                sock.sendto(msg, addr)

            # If there is data, we accept it and print it out
            elif (decoded['data']):
                # Send back an ack to the sender if received data in order
                if decoded['seq_num'] == expected_sequence:
                    log("[recv data] " + str(decoded['seq_num']) + " (" + str(len(decoded['data'])) + ") ACCEPTED (in-order)")
                    sys.stdout.write(decoded['data'])
                    expected_sequence += len(decoded['data'])

                    # log("expected next sequence" + str(expected_sequence))

                    # msg = json.dumps({"ack": decoded['seq_num'] + len(decoded['data']), "syn": False})
                    log("[sending ack] " + str(decoded['seq_num'] + len(decoded['data'])))
                    msg = json.dumps({"ack": decoded['seq_num'] + len(decoded['data']), "syn": False, "fin": False})
                    if sock.sendto(msg, addr) < len(msg):
                        log("[error] unable to fully send packet")

                    # check buffer to see if can now print packets already received after after this one
                    print_buffered_packets(expected_sequence)

                # if data received out of order, buffer it
                elif decoded['seq_num'] > expected_sequence:
                    # buffer data until received packets that come before it
                    log("[buffering data] " + str(decoded['seq_num']) + " (" + str(len(decoded['data'])) + ") ACCEPTED (out-of-order)")
                    buffer[decoded['seq_num']] = decoded['data']

                    # send ACK to sender
                    msg = json.dumps({"ack": decoded['seq_num'] + len(decoded['data']), "syn": False})
                    log("[sending ack] " + str(decoded['seq_num'] + len(decoded['data'])))
                    # log("About to send " + msg)
                    if sock.sendto(msg, addr) < len(msg):
                        log("[error] unable to fully send packet")

                # dropped ACK
                elif (decoded['seq_num']%MSS) == syn_num and decoded['seq_num'] < expected_sequence: # duplicate data, but sender didn't receive a previous ACK
                    msg = json.dumps({"ack": decoded['seq_num'] + len(decoded['data']), "syn": False, "fin": False})

                    log("[ack retransmission] received " + str(decoded['seq_num']) + " expected " + str(expected_sequence))
                    if sock.sendto(msg, addr) < len(msg): # just resend ACK, ignore data
                        log("[error] unable to fully send packet")

        except (ValueError, KeyError, TypeError) as e:
            log("[recv corrupt packet]")
            raise e
    else:
        log("[error] timeout")
        sys.exit(-1)
